apiVersion: v1
kind: Pod
metadata:
  name: my-config-pod
spec:
  containers:
    - name: my-test-container
      image: busybox
      command: [ "/bin/sh"]
      args: ["-c", "while true; do echo hello; sleep 1000;done"]
      envFrom:
      - configMapRef:
          name: mytest-config
